version: "3.9"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=perform
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: perform
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
